openapi: 3.0.0
info:
  title: StarWars Client API
  version: 1.0.0
paths:
  /starwars/character:
    post:
      summary: Crea un personaje de StarWars en la base de datos según su ID en SWAPI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: El ID del personaje en SWAPI
      responses:
        "200":
          description: Datos guardados correctamente
        "400":
          description: Error en la petición
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string
              example:
                message: "Error en la petición"
        "500":
          description: Error en el servidor
    get:
      summary: Devuelve todos los personajes almacenados
      responses:
        "200":
          description: Lista de personajes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    nombre:
                      type: string
                    altura:
                      type: string
