# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sebas1803
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-starwars-indra-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-starwars-indra-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/StarWarsPeople
        - arn:aws:dynamodb:us-east-1:*:table/StarWarsStarships
        - arn:aws:dynamodb:us-east-1:*:table/StarWarsPlanets

functions:
  handler:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  # People endpoints
  createCharacter:
    handler: src/people/createData.createData
    events:
      - httpApi:
          path: /starwars/people
          method: post

  getAllPeople:
    handler: src/people/getAllData.getAllData
    events:
      - httpApi:
          path: /starwars/people
          method: get

  getCharacterById:
    handler: src/people/getDataById.getDataById
    events:
      - httpApi:
          path: /starwars/people/{id}
          method: get

  # Starships endpoints
  createStarship:
    handler: src/starships/createStarship.createStarship
    events:
      - httpApi:
          path: /starwars/starships
          method: post

  getAllStarships:
    handler: src/starships/getAllStarships.getAllStarships
    events:
      - httpApi:
          path: /starwars/starships
          method: get

  getStarshipById:
    handler: src/starships/getStarshipById.getStarshipById
    events:
      - httpApi:
          path: /starwars/starships/{id}
          method: get

  # Planets endpoints
  createPlanet:
    handler: src/planets/createPlanet.createPlanet
    events:
      - httpApi:
          path: /starwars/planets
          method: post

  getAllPlanets:
    handler: src/planets/getAllPlanets.getAllPlanets
    events:
      - httpApi:
          path: /starwars/planets
          method: get

  getPlanetById:
    handler: src/planets/getPlanetById.getPlanetById
    events:
      - httpApi:
          path: /starwars/planets/{id}
          method: get

# Set dynamoDB Connection
resources:
  Resources:
    # DynamoDB Tables
    StarWarsCharacters:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarWarsPeople
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    StarWarsStarships:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarWarsStarships
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    StarWarsPlanets:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarWarsPlanets
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
