# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sebas1803
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-starwars-indra-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-starwars-indra-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
